### ISSUE TITLE
Truncated description when using format detail

### ISSUE THREAD

**Issue by sangorrin** [FedericoCeratto/debian-debsecan#100]
Hi,

Is there a reason for truncating the CVE description when you use `--format detail`. If the user asks for the details, the logical thing would be to output the whole description. You could also enable `--line-length` for the detail format, just in case there is a use case for truncating the description.

Thanks,
Daniel

**Comment by FedericoCeratto** [comment]
Please use https://salsa.debian.org/security-tracker-team/security-tracker
