### ISSUE TITLE
404 on almost every suite

### ISSUE THREAD

**Issue by jamenlang** [FedericoCeratto/debian-debsecan#99]
my headless box gets a 404 with the "debsecan --suite jessie --format packages --only-fixed" flags.

If I try to browse to https://security-tracker.debian.org/tracker/debsecan/release/1/jessie I get an "Object not found" landing page.

This doesn't seem to be debsecan so much as a problem with the security tracker on debian.org.

**Comment by FedericoCeratto** [comment]
Please use https://salsa.debian.org/security-tracker-team/security-tracker
